

nav:
- Overview: index.md
- Developer Guide: go-pkg/index.md
- Command Line Interface:
  - Get Started:
    - Installation: cli/get-started/installation.md
    - Authentication: cli/get-started/authentication.md
    - Bootstrap: cli/get-started/bootstrap.md
  - Command Reference: cli/commands/lkctl.md
- Releases â§‰: https://github.com/baptistegh/go-lakekeeper/releases
repo_url: https://github.com/baptistegh/go-lakekeeper
site_name: go-lakekeeper
# site_url: !ENV READTHEDOCS_CANONICAL_URL
strict: true
theme:
  favicon: assets/bear.svg
  font:
    text: Work Sans
  logo: assets/bear.svg
  name: material
  palette:
  - media: '(prefers-color-scheme: light)'
    primary: indigo
    scheme: default
    toggle:
      icon: material/brightness-7
      name: Switch to dark mode
  - media: '(prefers-color-scheme: dark)'
    primary: indigo
    scheme: slate
    toggle:
      icon: material/brightness-4
      name: Switch to light mode
